web:
  ports:
   - 80:3000
  environment:
   - PORT=3000
   - MONGO=mongodb://db:27017/meetup
   - REDIS=redis://redis:6379
   - FACEBOOK_APP_ID=xxx
   - FACEBOOK_APP_SECRET=xxx
   - APNS_ENV = sandbox
   - APNS_CERT = ../config/certificates/sandbox/cert.pem
   - APNS_KEY = ../config/certificates/sandbox/key.pem
   - GCM_API_KEY = xxx
db:
  ports:
   - 27017:27017
redis:
  ports:
   - 6379:6379